#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning log*"
rm log*
echo "Cleaning timestep*"
rm -rf 0.0*
rm -rf *e-0*
echo "Cleaning initial timestep*"
rm -rf 0/
echo "Cleaning processor*"
rm -r processor*
echo "Cleaning polyMesh/"
rm -r constant/polyMesh
echo "Cleaning VTK/"
rm -r VTK/
