#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

if [ -e DNN_model.pt ]
then
    echo "DNN_model.pt exists. Make sure correct DNN model has been used!"
else
    echo "DNN_model.pt not exist. Downloading ..."
    wget https://store.aissquare.com/models/5e1232cd-c23f-489f-9db4-ee09592beeb1/DNN_model.zip
    unzip DNN_model.zip
    cp ./DNN_model/C2H4/DNN_model.pt .
    cp ./DNN_model/C2H4/Wu24sp.yaml .
fi

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfLowMachFoam

runApplication blockMesh
runApplication decomposePar
runApplication mpirun -np 8 --allow-run-as-root $application -parallel
