#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfHighSpeedFoam

runApplication blockMesh
runApplication $application

# To convert position file of droplet, use this commend:
# dfHighSpeedFoam -postProcess -dict system/positionConvertDict