#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning log.*"
rm log.* log*
echo "Cleaning processor*"
rm -r processor*
echo "Cleaning polyMesh/"
rm -r constant/polyMesh
echo "Cleaning time steps"
rm -r 0.00*
echo "Cleaning postProcessing"
rm -r postProcessing/
