#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfLowMachFoam

runApplication blockMesh
runApplication decomposePar
runApplication mpirun -np 8 $application -parallel

runApplication reconstructPar -time 1e-4,2e-4,3e-4,4e-4,5e-4
runApplication postProcess -func sample -time 1e-4,2e-4,3e-4,4e-4,5e-4
