#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning log*"
rm log*
echo "Cleaning timestep*"
rm -rf 0.000374
rm -rf 0.000375
rm -rf 0.000376
rm -rf 0.000377
rm -rf 0.000378
rm -rf 0.000379
rm -rf 0.00038*
rm -rf 0.00039*
rm -rf 0.0004*
rm -rf 0.0005*
rm -rf 0.0006*
rm -rf 0.0007*
rm -rf 0.0008*
rm -rf 0.0009*
echo "Cleaning initial timestep*"
rm -rf 0/
echo "Cleaning processor*"
rm -r processor*
echo "Cleaning polyMesh/"
rm -r constant/polyMesh
echo "Cleaning VTK/"
rm -r VTK/
